name: Scheduled PR merges

on:
    # - cron: "0 9 * * *"   # 09:00 UTC
  workflow_dispatch:      # allow manual trigger

permissions:
    contents: write
    pull-requests: write

jobs:
  merge-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge PR 1
        run: gh pr merge 12 --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait 5 minutes
        run: sleep 300

      - name: Merge PR 2
        run: gh pr merge 13 --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait 5 minutes
        run: sleep 300

      - name: Merge PR 3
        run: gh pr merge 14 --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}